services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./media/:/app/media/
      - ./static/:/app/static/
      - ./docker/conf.d/:/etc/nginx/conf.d/:ro
    depends_on:
      - web
  redis:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
     - ./media/:/app/media/
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
      - migrations
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A pictures_store worker -l info
    entrypoint: ""
    env_file:
      - .env
    depends_on:
      - db
      - migrations
      - redis
    volumes:
      - ./media/:/app/media/
    restart: on-failure
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    command: python manage.py migrate
  db:
    image: postgres:14.6-alpine
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data:

