# Generated by Django 4.2.1 on 2023-05-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_alter_galery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.RenameField(
            model_name='galery',
            old_name='picture',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='galery',
            old_name='description',
            new_name='prompt',
        ),
    ]
