# Generated by Django 4.2.1 on 2023-05-16 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galery", "0003_alter_galery_options_rename_picture_galery_imgs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="galery",
            old_name="imgs",
            new_name="img",
        ),
    ]
