# Generated by Django 4.2.1 on 2023-05-25 16:01

from django.db import migrations, models
import galery.models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_alter_galery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='img',
            field=models.ImageField(upload_to=galery.models.upload_to_galery),
        ),
    ]
